
export default {
    environment: process.env.NODE_ENV,
    INDEX_VIEW_NINE : [
        {id:'1',name:'泵浦狀況',type:'Pump',sort:'1'},
        {id:'2',name:'水位狀況',type:'Waterlevel',sort:'2'},
        {id:'3',name:'升降機運行狀況',type:'Elevator',sort:'3'},
        {id:'4',name:'排煙機狀況',type:'Smoke',sort:'4'},
        {id:'5',name:'發電機狀況',type:'Generator',sort:'5'},
        {id:'6',name:'電源供給狀況',type:'Power',sort:'6'},
        {id:'7',name:'空調主機',type:'Air',sort:'7'},
        {id:'8',name:'待確認8',type:'x',sort:'8'},
        {id:'9',name:'待確認9',type:'x',sort:'9'},
        {id:'10',name:'待確認10',type:'x',sort:'10'},
        {id:'11',name:'待確認11',type:'x',sort:'11'},
        {id:'12',name:'待確認12',type:'x',sort:'12'},
        {id:'13',name:'待確認13',type:'x',sort:'13'},
        {id:'14',name:'待確認14',type:'x',sort:'14'}
    ],
    Equipment:[
        {id:'1',name:'火災表示',imgSrc:require("../assets/equipment/1.png")},
        {id:'2',name:'室內消防栓設備',imgSrc:require("../assets/equipment/2.png")},
        {id:'3',name:'自動撒水設備',imgSrc:require("../assets/equipment/3.png")},
        {id:'4',name:'水霧滅火設備',imgSrc:require("../assets/equipment/4.png")},
        {id:'5',name:'泡沫滅火設備',imgSrc:require("../assets/equipment/5.png")},
        {id:'6',name:'惰性氣體滅火設備',imgSrc:require("../assets/equipment/6.png")},
        {id:'7',name:'鹵化烴滅火設備',imgSrc:require("../assets/equipment/7.png")},
        {id:'8',name:'乾粉滅火設備',imgSrc:require("../assets/equipment/8.png")},
        {id:'9',name:'室外消防栓設備',imgSrc:require("../assets/equipment/9.png")},
        {id:'10',name:'偵煙式探測器',imgSrc:require("../assets/equipment/10.png")},
        {id:'11',name:'光電式分離型探測器',imgSrc:require("../assets/equipment/11.png")},
        {id:'12',name:'高壓氣體慶儲存場所',imgSrc:require("../assets/equipment/12.png")},
        {id:'13',name:'公共危險物品儲存場所',imgSrc:require("../assets/equipment/13.png")},
        {id:'14',name:'感熱式探測器',imgSrc:require("../assets/equipment/14.png")},
        {id:'15',name:'火焰式探測器',imgSrc:require("../assets/equipment/15.png")},
        {id:'16',name:'火警發信機',imgSrc:require("../assets/equipment/16.png")},
        {id:'17',name:'瓦斯漏氣檢知器',imgSrc:require("../assets/equipment/17.png")},
        {id:'18',name:'緊急電話',imgSrc:require("../assets/equipment/18.png")},
        {id:'19',name:'緊急廣播設備',imgSrc:require("../assets/equipment/19.png")},
        {id:'20',name:'避難引導燈具',imgSrc:require("../assets/equipment/20.png")},
        {id:'21',name:'排煙口',imgSrc:require("../assets/equipment/21.png")},
        {id:'22',name:'加壓送水裝置',imgSrc:require("../assets/equipment/22.png")},
        {id:'23',name:'防火門',imgSrc:require("../assets/equipment/23.png")},
        {id:'24',name:'防火捲門',imgSrc:require("../assets/equipment/24.png")},
        {id:'25',name:'防煙垂壁',imgSrc:require("../assets/equipment/25.png")},
        {id:'26',name:'特別安全梯排煙口進風口',imgSrc:require("../assets/equipment/26.png")},
        {id:'27',name:'自然排煙窗',imgSrc:require("../assets/equipment/27.png")},
        {id:'28',name:'防火閘門',imgSrc:require("../assets/equipment/28.png")},
        {id:'29',name:'緊急昇降機',imgSrc:require("../assets/equipment/29.png")},
        {id:'30',name:'連結送水口',imgSrc:require("../assets/equipment/30.png")},
        {id:'31',name:'緊急電源插座設備',imgSrc:require("../assets/equipment/31.png")},
        {id:'32',name:'無線電通信輔助設備',imgSrc:require("../assets/equipment/32.png")},
        {id:'33',name:'防災中心',imgSrc:require("../assets/equipment/33.png")},
        {id:'34',name:'排煙機',imgSrc:require("../assets/equipment/34.png")},
    ]

}